# Run when the PR is created, updated with a new commit, or re-opened after closed

name: Pull Request
on: 
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  pr_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Build Docker container
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          load: true
          tags: ${{ github.repository }}:${{ github.head_ref }}
      
      # LINTER
      - name: Run linter
        run: docker run ${{ github.repository }}:${{ github.head_ref }} cat /etc/os-release
        # run: echo 'Run your linter here'
      
      # TESTS
      - name: Run tests
        run: cat /etc/os-release
      
      # SECURITY
      - name: Run Security Scans
        run: echo 'Run your security scans'

      # CODE QUALITY
      - name: Run Code Quality
        run: echo 'Run code quality scans'