# # Run when the PR is closed
# # ---

# name: Tag main branch
# on: 
#   pull_request:
#     # types: [closed]
#     types: [opened, reopened, synchronize, labeled, unlabeled]

# jobs:
#   tag_main:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Dump GitHub context
#         env:
#           GITHUB_CONTEXT: ${{ toJson(github) }}
#         run: echo "$GITHUB_CONTEXT"
#       - name: Dump GitHub labels context
#         env:
#           GITHUB_CONTEXT: ${{ toJson(github.event.pull_request.labels) }}
#         run: echo "$GITHUB_CONTEXT"
#       - name: Hello major release
#         if: "contains(github.event.pull_request.labels.*.name, 'release-major')"
#         run: echo "Found major label!"
#       - name: Hello minor release
#         if: "contains(github.event.pull_request.labels.*.name, 'release-minor')"
#         run: echo "Found minor label!"
#       - name: Hello minor release
#         if: "contains(github.event.pull_request.labels.*.name, 'release-patch')"
#         run: echo "Found patch label!"  
#       - name: Hello world
#         run: echo "Hello world" 
 
