# Run when the PR is closed
# -

name: Tag main branch
on: 
  pull_request_target:
    # types: [closed]
    types: [opened, reopened, synchronize]

jobs:
  tag_main:
    runs-on: ubuntu-latest
    steps:
      - name: Hello major release
        if: "contains(github.event.labels.*.name, 'release-major')"
        run: echo "Found major label!"
      # - name: Hello minor release
      #   if: "contains(github.event.labels.*.name, 'release-minor')"
      #   run: echo "Found minor label!"
      # - name: Hello minor release
      #   if: "contains(github.event.labels.*.name, 'release-pathc')"
      #   run: echo "Found patch label!"  
